server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,metrics,system

offlinechat:
  ollama-base-url: http://localhost:11434

spring:
  application:
    name: offlinechat-backend
